/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2018-04-15 14:34:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"scripts/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\"#testJson\").click(function(){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"testJson\",\r\n");
      out.write("\t\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tfor(var i =0 ;i<data.length;i++){\r\n");
      out.write("\t\t\t\t\t\t\tvar emp = data[i];\r\n");
      out.write("\t\t\t\t\t\t\talert(emp.id + \" , \" + emp.lastName + \" , \" +emp.email  );\r\n");
      out.write("\t\t\t\t\t\t\t//作业:  异步请求json数据，显示员工信息列表. \r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn false ;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t\r\n");
      out.write("\t<form action=\"testFileUpload\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\tFile: <input type=\"file\" name=\"uploadFile\"/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\tDesc: <input type=\"text\" name=\"desc\"/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"上传\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"testResponseEntity\">下载美女图片</a>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<a href=\"testHttpEntity\"> Test HttpEntity</a>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<form action=\"testRequestBody\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\tFile: <input type=\"file\" name=\"uploadFile\"/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\tDesc: <input type=\"text\" name=\"desc\"/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"@RequestBody\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<a id=\"testJson\" href=\"testJson\">Test Json</a>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<a href=\"emps\">List All Emps</a>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<a href=\"testRedirect\">Test Redirect</a>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"testMyView\">Test MyView</a>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"testModelOrMap\">Test  Model  Map</a>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"testModelAndView\"> Test ModelAndView </a>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"testServletAPI\">Test ServletAPI</a>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<form action=\"testPOJO\" method=\"post\">\r\n");
      out.write("\t\tusername: <input type=\"text\" name=\"username\"/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\tpassword: <input type=\"password\" name=\"password\"/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\temail: <input type=\"text\" name=\"email\"/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\tage : <input type=\"text\" name=\"age\"/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\tprovince:<input type=\"text\" name=\"address.province\"/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\tcity:<input type=\"text\" name=\"address.city\"/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"注册\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"testCookieValue\">Test CookieValue</a>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"testRequestHeader\">Test RequestHeader</a>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<a href=\"testRequestParam?username=tom&age=22\">Test RequestParam</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
