package com.atguigu.mybatis.dao;

import com.atguigu.mybatis.beans.Department;
import java.util.List;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbggenerated Fri Apr 20 21:10:04 CST 2018
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbggenerated Fri Apr 20 21:10:04 CST 2018
     */
    List<Department> selectAll();
}