/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2018-04-30 14:23:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/main.css\">\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.tree li {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable tbody tr:nth-child(odd){background:#F4F4F4;}\r\n");
      out.write("\ttable tbody td:nth-child(even){color:#C00;}\r\n");
      out.write("\t</style>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <div><a class=\"navbar-brand\" style=\"font-size:32px;\" href=\"#\">众筹平台 - 用户维护</a></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li style=\"padding-top:8px;\">\r\n");
      out.write("\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t  <button type=\"button\" class=\"btn btn-default btn-success dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t  </button>\r\n");
      out.write("\t\t\t\t\t  <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\"></i> 个人设置</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-comment\"></i> 消息</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/index.htm\"><i class=\"glyphicon glyphicon-off\"></i> 退出系统</a></li>\r\n");
      out.write("\t\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("            <li style=\"margin-left:10px;padding-top:8px;\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-danger\">\r\n");
      out.write("\t\t\t\t  <span class=\"glyphicon glyphicon-question-sign\"></span> 帮助\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <form class=\"navbar-form navbar-right\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("\t\t\t<div class=\"tree\">\r\n");
      out.write("\t\t\t\t<ul style=\"padding-left:0px;\" class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item tree-closed\" >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"main.html\"><i class=\"glyphicon glyphicon-dashboard\"></i> 控制面板</a> \r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t<span><i class=\"glyphicon glyphicon glyphicon-tasks\"></i> 权限管理 <span class=\"badge\" style=\"float:right\">3</span></span> \r\n");
      out.write("\t\t\t\t\t\t<ul style=\"margin-top:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"user.html\" style=\"color:red;\"><i class=\"glyphicon glyphicon-user\"></i> 用户维护</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"role.html\"><i class=\"glyphicon glyphicon-king\"></i> 角色维护</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"permission.html\"><i class=\"glyphicon glyphicon-lock\"></i> 许可维护</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item tree-closed\">\r\n");
      out.write("\t\t\t\t\t\t<span><i class=\"glyphicon glyphicon-ok\"></i> 业务审核 <span class=\"badge\" style=\"float:right\">3</span></span> \r\n");
      out.write("\t\t\t\t\t\t<ul style=\"margin-top:10px;display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"auth_cert.html\"><i class=\"glyphicon glyphicon-check\"></i> 实名认证审核</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"auth_adv.html\"><i class=\"glyphicon glyphicon-check\"></i> 广告审核</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"auth_project.html\"><i class=\"glyphicon glyphicon-check\"></i> 项目审核</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item tree-closed\">\r\n");
      out.write("\t\t\t\t\t\t<span><i class=\"glyphicon glyphicon-th-large\"></i> 业务管理 <span class=\"badge\" style=\"float:right\">7</span></span> \r\n");
      out.write("\t\t\t\t\t\t<ul style=\"margin-top:10px;display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"cert.html\"><i class=\"glyphicon glyphicon-picture\"></i> 资质维护</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"type.html\"><i class=\"glyphicon glyphicon-equalizer\"></i> 分类管理</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"process.html\"><i class=\"glyphicon glyphicon-random\"></i> 流程管理</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"advertisement.html\"><i class=\"glyphicon glyphicon-hdd\"></i> 广告管理</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"message.html\"><i class=\"glyphicon glyphicon-comment\"></i> 消息模板</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"project_type.html\"><i class=\"glyphicon glyphicon-list\"></i> 项目分类</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"tag.html\"><i class=\"glyphicon glyphicon-tags\"></i> 项目标签</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item tree-closed\" >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"param.html\"><i class=\"glyphicon glyphicon-list-alt\"></i> 参数管理</a> \r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t  <div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t<h3 class=\"panel-title\"><i class=\"glyphicon glyphicon-th\"></i> 数据列表</h3>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"panel-body\">\r\n");
      out.write("<form class=\"form-inline\" role=\"form\" style=\"float:left;\">\r\n");
      out.write("  <div class=\"form-group has-feedback\">\r\n");
      out.write("    <div class=\"input-group\">\r\n");
      out.write("      <div class=\"input-group-addon\">查询条件</div>\r\n");
      out.write("      <input id=\"querytext\" class=\"form-control has-success\" type=\"text\" placeholder=\"请输入查询条件\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <button id=\"querybtn\" type=\"button\" class=\"btn btn-warning\"><i class=\"glyphicon glyphicon-search\"></i> 查询</button>\r\n");
      out.write("</form>\r\n");
      out.write("<button type=\"button\" class=\"btn btn-danger\" style=\"float:right;margin-left:10px;\"><i class=\" glyphicon glyphicon-remove\"></i> 删除</button>\r\n");
      out.write("<button type=\"button\" class=\"btn btn-primary\" style=\"float:right;\" onclick=\"window.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/toAdd.htm'\"><i class=\"glyphicon glyphicon-plus\"></i> 新增</button>\r\n");
      out.write("<br>\r\n");
      out.write(" <hr style=\"clear:both;\">\r\n");
      out.write("          <div class=\"table-responsive\">\r\n");
      out.write("            <table class=\"table  table-bordered\">\r\n");
      out.write("              <thead>\r\n");
      out.write("                <tr >\r\n");
      out.write("                  <th width=\"30\">#</th>\r\n");
      out.write("\t\t\t\t  <th width=\"30\"><input type=\"checkbox\"></th>\r\n");
      out.write("                  <th>账号</th>\r\n");
      out.write("                  <th>名称</th>\r\n");
      out.write("                  <th>邮箱地址</th>\r\n");
      out.write("                  <th width=\"100\">操作</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody>\r\n");
      out.write("              </tbody>\r\n");
      out.write("\t\t\t  <tfoot>\r\n");
      out.write("\t\t\t     <tr >\r\n");
      out.write("\t\t\t\t     <td colspan=\"6\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t </ul>\r\n");
      out.write("\t\t\t\t\t </td>\r\n");
      out.write("\t\t\t\t </tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t  </tfoot>\r\n");
      out.write("            </table>\r\n");
      out.write("          </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/docs.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery/layer/layer.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            $(function () {\r\n");
      out.write("\t\t\t    $(\".list-group-item\").click(function(){\r\n");
      out.write("\t\t\t\t    if ( $(this).find(\"ul\") ) {\r\n");
      out.write("\t\t\t\t\t\t$(this).toggleClass(\"tree-closed\");\r\n");
      out.write("\t\t\t\t\t\tif ( $(this).hasClass(\"tree-closed\") ) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"ul\", this).hide(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"ul\", this).show(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t    //异步请求\r\n");
      out.write("\t\t\t    var pageno = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pageno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\t\t    if(pageno == \"\"){\r\n");
      out.write("                 QueryPage(1);\r\n");
      out.write("\t\t\t    }else{\r\n");
      out.write("\t\t\t    \tQuerPage(pageno);\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("            \tvar jsonObj = {\r\n");
      out.write("            \t\t\tpagesize:2\r\n");
      out.write("            \t};\r\n");
      out.write("            function QueryPage(pageno){\r\n");
      out.write("            \t\t\tjsonObj.pageno = pageno;\r\n");
      out.write("            \tvar index=-1;\r\n");
      out.write("    \t\t    $.ajax({\r\n");
      out.write("    \t\t    \t\ttype:\"post\",\r\n");
      out.write("    \t\t    \t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/QueryPage.do\",\r\n");
      out.write("    \t\t    \t\tdata:jsonObj,\r\n");
      out.write("    \t\t    \t\tbeforeSend:function(){\r\n");
      out.write("    \t\t    \t\t\tindex = layer.load(2, {time: 10*1000});\r\n");
      out.write("                \t\t\treturn true ;\r\n");
      out.write("    \t\t    \t\t           },\r\n");
      out.write("    \t\t             success:function(result){\r\n");
      out.write("    \t\t            \t layer.close(index);\r\n");
      out.write("    \t\t    \t              if(result.success){\r\n");
      out.write("    \t\t    \t            \t var page = result.data;\r\n");
      out.write("    \t\t    \t            \t var list = page.datas;\r\n");
      out.write("    \t\t    \t            \t var content = \"\";\r\n");
      out.write("    \t\t    \t            \t $.each(list,function(i,e){\r\n");
      out.write("    \t\t    \t            \t\t content+='<tr>';\r\n");
      out.write("    \t\t    \t            \t\t content+='  <td>'+(i+1)+'</td>';\r\n");
      out.write("    \t\t    \t            \t\t content+='  <td><input type=\"checkbox\"></td>';\r\n");
      out.write("    \t\t    \t            \t\t content+='  <td>'+e.loginacct+'</td>';\r\n");
      out.write("    \t\t    \t            \t\t content+='  <td>'+e.username+'</td>';\r\n");
      out.write("    \t\t    \t            \t\t content+='  <td>'+e.email+'</td>';\r\n");
      out.write("    \t\t    \t            \t\t content+='  <td>';\r\n");
      out.write("    \t\t    \t            \t\t content+='\t  <button type=\"button\" class=\"btn btn-success btn-xs\"><i class=\" glyphicon glyphicon-check\"></i></button>';\r\n");
      out.write("    \t\t    \t            \t\t content+='\t  <button type=\"button\" class=\"btn btn-primary btn-xs\"><i class=\" glyphicon glyphicon-pencil\"></i></button>';\r\n");
      out.write("    \t\t    \t            \t\t content+='\t  <button type=\"button\" class=\"btn btn-danger btn-xs\"><i class=\" glyphicon glyphicon-remove\"></i></button>';\r\n");
      out.write("    \t\t    \t            \t\t content+='  </td>';\r\n");
      out.write("    \t\t    \t            \t\t content+='</tr> ';\r\n");
      out.write("    \t\t    \t            \t\t });\r\n");
      out.write("    \t\t    \t            \t $(\"tbody\").html(content);\r\n");
      out.write("    \t\t    \t            \t /* =============================== */\r\n");
      out.write("    \t\t\t\t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t\t\t\t\tvar navcontent ='';\r\n");
      out.write("    \t\t\t\t\t\t\t\t\tif(page.pageno == 1){\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\tnavcontent +=' <li class=\"disabled\"><a>上一页</a></li>';\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\tnavcontent += '<li><a onclick=\"QueryPage('+(page.pageno-1)+')\">上一页</a></li>';\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\tfor(var i = 1;i<=page.totalno;i++){\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\tnavcontent +='<li ';\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\tif(page.pageno == i){   \t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\tnavcontent +='class=\"active\"';\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\tnavcontent +='><a onclick=\"QueryPage('+i+')\">'+i+'</a></li>';\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t\t\t\t\tif(page.pageno == page.totalno){\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\tnavcontent +=' <li class=\"disabled\"><a>下一页</a></li>';\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\tnavcontent += '<li><a onclick=\"QueryPage('+(page.pageno+1)+')\">下一页</a></li>';\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t$(\".pagination\").html(navcontent);\r\n");
      out.write("    \t\t    \t            \t }else{\r\n");
      out.write("    \t\t    \t            \t\t layer.msg(result.message, {time:1000, icon:5, shift:6}); \r\n");
      out.write("    \t\t    \t            \t }\r\n");
      out.write("    \t\t    \t              }\r\n");
      out.write("    \t\t            \t \r\n");
      out.write("    \t\t                     }\r\n");
      out.write("    \t\t    );\r\n");
      out.write("            \t\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("           $(\"#querybtn\").click(function(){\r\n");
      out.write("        \t   var querytext = $(\"#querytext\").val();\r\n");
      out.write("        \t   //alert(querytext);\r\n");
      out.write("        \t   jsonObj.querytext = querytext;\r\n");
      out.write("        \t   QueryPage(1);\r\n");
      out.write("           });\r\n");
      out.write("        </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
